-- default config
require("solarized").setup({
	transparent = false, -- enable transparent background
	styles = {
		comments = {},
		functions = {},
		variables = {},
		numbers = {},
		constants = {},
		parameters = { italic = true, bold = false },
		keywords = { bold = true },
		types = { italic = false, bold = false },
	},
	enables = {
		bufferline = true,
		cmp = true,
		diagnostic = true,
		dashboard = true,
		editor = true,
		gitsign = true,
		hop = true,
		indentblankline = true,
		lsp = true,
		lspsaga = true,
		navic = true,
		neotree = true,
		notify = true,
		semantic = true,
		syntax = true,
		telescope = true,
		tree = true,
		treesitter = true,
		whichkey = true,
		mini = true,
	},
	highlights = {},
	colors = {},
})
